apiVersion: v1
kind: Service
metadata:
  name: mcp-sample-server
  labels:
    app.kubernetes.io/name: mcp-sample-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mcp-sample-server
